# Generated by Django 6.1.1 on 2026-09-14 22:17

import django.db.models.deletion
import django.utils.timezone
import iguana.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('stage_name', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('bio_es', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('home_city', models.CharField(blank=True, max_length=120)),
                ('residency', models.CharField(blank=True, max_length=200)),
                ('socials', models.JSONField(blank=True, default=dict, help_text='{"instagram": "https://..."}')),
                ('reels', models.JSONField(blank=True, default=list, help_text='[{"title": "", "url": "", "posterUrl": null}]')),
                ('sort_order', models.IntegerField(default=0)),
                ('listed', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(help_text='Show day. Imported rows are midnight in Cancun.')),
                ('doors_open', models.CharField(blank=True, help_text='24h clock, e.g. 19:30', max_length=10)),
                ('show_time', models.CharField(blank=True, help_text='24h clock, e.g. 20:00', max_length=10)),
                ('end_time', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('long_description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image_url_mobile', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SOLD_OUT', 'Sold Out'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('UNLISTED', 'Unlisted'), ('MEMBERS', 'Members only')], default='PUBLIC', max_length=10)),
                ('ticketing_type', models.CharField(choices=[('INTERNAL', 'Sold here'), ('EXTERNAL', 'External link')], default='INTERNAL', max_length=10)),
                ('external_ticket_url', models.URLField(blank=True, max_length=500)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('language', models.CharField(default='en', max_length=5)),
                ('age_restriction', models.CharField(blank=True, max_length=40)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('reviews', models.JSONField(blank=True, default=list, help_text='[{"quote": "", "stars": 5, "source": ""}]')),
                ('venue_label', models.CharField(blank=True, help_text='Venue name as exported, when no Venue row matched.', max_length=200)),
                ('members_eligible', models.BooleanField(default=True, help_text='Member free tickets / guest discount apply.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='FormEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('intent', models.CharField(choices=[('show_request', 'show_request'), ('contact', 'contact'), ('newsletter', 'newsletter'), ('external_lead', 'external_lead'), ('custom', 'custom')], default='contact', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('success_message', models.CharField(blank=True, default='Thanks! We will be in touch soon.', max_length=300)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteFile',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Brand stems such as site-hero-video are matched by the site.', max_length=255)),
                ('file', models.FileField(upload_to='files/%Y/%m/')),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreCollection',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, default='Mexico', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('time_zone', models.CharField(default='America/Cancun', max_length=60)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('wheelchair_accessible', models.BooleanField(blank=True, null=True)),
                ('listed', models.BooleanField(default=True, help_text='Show on the public locations pages.')),
            ],
            options={
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('fields', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('visitor_key', models.CharField(blank=True, max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='catalog.formendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('external_url', models.URLField(blank=True, help_text='Where "Buy" sends people until on-site merch checkout exists.', max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('collections', models.ManyToManyField(blank=True, related_name='products', to='catalog.storecollection')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.storeproduct')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoreVariant',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default', max_length=120)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('price_cents', models.PositiveIntegerField()),
                ('compare_at_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('available_quantity', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.storeproduct')),
            ],
            options={
                'ordering': ['sort_order', 'price_cents'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('price_cents', models.PositiveIntegerField()),
                ('member_price_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('member_access', models.CharField(choices=[('ALL', 'Everyone'), ('MEMBERS_ONLY', 'Members only'), ('NON_MEMBERS', 'Non-members only')], default='ALL', max_length=14)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='catalog.event')),
            ],
            options={
                'ordering': ['sort_order', 'price_cents'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='catalog.tour'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='catalog.venue'),
        ),
        migrations.CreateModel(
            name='LineupEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=60)),
                ('headliner', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_entries', to='catalog.artist')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup', to='catalog.event')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('event', 'artist')},
            },
        ),
    ]
