# Generated by Django 6.1.1 on 2026-09-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image_url',
            field=models.CharField(blank=True, help_text='Absolute URL or /media/... path', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='external_ticket_url',
            field=models.CharField(blank=True, help_text='Absolute URL or /media/... path', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.CharField(blank=True, help_text='Absolute URL or /media/... path', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url_mobile',
            field=models.CharField(blank=True, help_text='Absolute URL or /media/... path', max_length=500),
        ),
        migrations.AlterField(
            model_name='storecollection',
            name='image_url',
            field=models.CharField(blank=True, help_text='Absolute URL or /media/... path', max_length=500),
        ),
        migrations.AlterField(
            model_name='storeproductimage',
            name='url',
            field=models.CharField(help_text='Absolute URL or /media/... path', max_length=500),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_url',
            field=models.CharField(blank=True, help_text='Absolute URL or /media/... path', max_length=500),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image_url',
            field=models.CharField(blank=True, help_text='Absolute URL or /media/... path', max_length=500),
        ),
    ]
