# Generated by Django 6.1.1 on 2026-09-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_media_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='max_per_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Blank = 20', null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='pay_at_door',
            field=models.BooleanField(default=False, help_text='Reserve online, pay at the door. No online payment is taken for this type.'),
        ),
    ]
