# Generated by Django 6.1.1 on 2026-09-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_tickettype_max_per_order_tickettype_pay_at_door'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='description_es',
            field=models.CharField(blank=True, help_text='Spanish description; blank falls back.', max_length=300),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='name_es',
            field=models.CharField(blank=True, help_text='Spanish name; blank falls back to the name.', max_length=120),
        ),
    ]
