# Generated by Django 6.1.1 on 2026-09-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_tickettype_description_es_tickettype_name_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_es',
            field=models.TextField(blank=True, help_text='Spanish description; blank falls back.'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url_es',
            field=models.CharField(blank=True, help_text='Spanish poster; blank falls back.', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url_mobile_es',
            field=models.CharField(blank=True, help_text='Spanish mobile poster.', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='long_description_es',
            field=models.TextField(blank=True, help_text='Spanish long description; blank falls back.'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_es',
            field=models.CharField(blank=True, help_text='Spanish name; blank falls back to the name.', max_length=200),
        ),
    ]
