# Generated by Django 6.1.1 on 2026-09-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_event_description_es_event_image_url_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='is_addon',
            field=models.BooleanField(default=False, help_text='Offered as an upsell AFTER the details are filled in, not as a thing to choose first. The open mic seat is free; drinks are the sale.'),
        ),
    ]
