# Generated by Django 6.1.1 on 2026-09-22 01:58

import django.db.models.deletion
import iguana.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_tickettype_is_addon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('name_es', models.CharField(blank=True, help_text='Spanish name; blank falls back to the name.', max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'menu categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('name_es', models.CharField(blank=True, help_text='Spanish name; blank falls back to the name.', max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('description_es', models.CharField(blank=True, help_text='Spanish; blank falls back.', max_length=300)),
                ('price_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='mxn', max_length=3)),
                ('available', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.menucategory')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
