# Generated by Django 6.1.1 on 2026-09-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_menucategory_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='sold_elsewhere',
            field=models.PositiveIntegerField(default=0, help_text='Seats already gone through another channel, e.g. a guest promoter selling the same night on their own site. Counted against capacity so this checkout cannot oversell the room, and counted as taken so the page tells the truth about how full it is.'),
        ),
    ]
