# Generated by Django 6.1.1 on 2026-09-25 04:28

import django.db.models.deletion
import django.utils.timezone
import iguana.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_event_members_eligible'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='En español: es lo que ve el personal.', max_length=120)),
                ('area', models.CharField(choices=[('bar', 'Barra'), ('kitchen', 'Cocina'), ('supplies', 'Insumos')], default='bar', max_length=20)),
                ('unit', models.CharField(blank=True, help_text='bottle, case, kg, each. Free text on purpose.', max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('par', models.DecimalField(decimal_places=2, default=0, help_text='Reorder at or below this. 0 means never flag it.', max_digits=10)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['area', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryChange',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('who', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='catalog.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
