# Generated by Django 6.1.1 on 2026-09-25 04:51

import django.db.models.deletion
import iguana.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_inventoryitem_inventorychange'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemIngredient',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='catalog.inventoryitem')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='catalog.menuitem')),
            ],
            options={
                'ordering': ['inventory_item__name'],
                'constraints': [models.UniqueConstraint(fields=('menu_item', 'inventory_item'), name='one_row_per_ingredient_per_item')],
            },
        ),
    ]
