# Generated by Django 6.1.1 on 2026-09-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_menuitemingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('tables', models.PositiveSmallIntegerField(default=12, help_text='Cuántas mesas hay en el salón.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': 'floor settings',
                'verbose_name_plural': 'floor settings',
            },
        ),
    ]
