# Generated by Django 6.1.1 on 2026-09-28 19:02

import django.db.models.deletion
import django.utils.timezone
import iguana.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0013_floorsettings_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('role', models.CharField(choices=[('COMANDA', 'Comandas (barra)'), ('TICKET', 'Tickets (caja)')], max_length=10)),
                ('protocol', models.CharField(choices=[('EPSON', 'Epson Server Direct Print'), ('STAR', 'Star CloudPRNT')], default='EPSON', max_length=10)),
                ('token', models.CharField(default=iguana.ids.new_token, max_length=60, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, help_text='Invoice or ticket number.', max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(choices=[('MESERO', 'Mesero'), ('CAJERO', 'Cajero'), ('GERENTE', 'Gerente')], default='MESERO', max_length=10)),
                ('pin_hash', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'staff',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, help_text='Blank shows the number.', max_length=40)),
                ('shape', models.CharField(choices=[('SQUARE', 'Cuadrada'), ('ROUND', 'Redonda'), ('BAR', 'Barra')], default='SQUARE', max_length=10)),
                ('seats', models.PositiveIntegerField(default=4)),
                ('x', models.FloatField(default=5)),
                ('y', models.FloatField(default=5)),
                ('w', models.FloatField(default=12)),
                ('h', models.FloatField(default=12)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['zone__sort_order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('folio', models.PositiveIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada')], db_index=True, default='OPEN', max_length=10)),
                ('label', models.CharField(blank=True, help_text='For a check with no table: "Barra", a name.', max_length=60)),
                ('guests', models.PositiveIntegerField(default=1)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('bill_printed_at', models.DateTimeField(blank=True, null=True)),
                ('discount_cents', models.PositiveIntegerField(default=0)),
                ('discount_reason', models.CharField(blank=True, max_length=120)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('pay_token', models.CharField(default=iguana.ids.new_token, max_length=60, unique=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_checks', to='catalog.event')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.staff')),
                ('discount_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.staff')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='pos.staff')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='pos.table')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('done_at', models.DateTimeField(blank=True, help_text='Marked served on the bar screen.', null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to='pos.check')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.staff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost_cents', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos_cost', to='catalog.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('min_select', models.PositiveIntegerField(default=0)),
                ('max_select', models.PositiveIntegerField(default=1)),
                ('sort_order', models.IntegerField(default=0)),
                ('items', models.ManyToManyField(blank=True, related_name='modifier_groups', to='catalog.menuitem')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price_cents', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='pos.modifiergroup')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=80)),
                ('lines', models.JSONField(default=list)),
                ('status', models.CharField(db_index=True, default='QUEUED', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='pos.printer')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_cents', models.PositiveIntegerField(default=0, help_text='Total paid for this line.')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.inventoryitem')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(default='OPEN', max_length=10)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opening_cash_cents', models.PositiveIntegerField(default=0)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('counted_cash_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('counted_card_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shifts_closed', to='pos.staff')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts_opened', to='pos.staff')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.staff'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta (terminal)'), ('TRANSFER', 'Transferencia'), ('PHONE', 'Tarjeta (celular)'), ('COURTESY', 'Cortesía')], max_length=10)),
                ('status', models.CharField(default='PAID', max_length=10)),
                ('amount_cents', models.PositiveIntegerField()),
                ('tip_cents', models.PositiveIntegerField(default=0)),
                ('received_cents', models.PositiveIntegerField(default=0)),
                ('change_cents', models.PositiveIntegerField(default=0)),
                ('reference', models.CharField(blank=True, help_text='Terminal voucher or transfer reference.', max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=80)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.check')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='pos.shift')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.staff')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckLine',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('unit_price_cents', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('modifiers', models.JSONField(blank=True, default=list, help_text='[{"name": "", "priceCents": 0}]')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('seat', models.PositiveIntegerField(blank=True, null=True)),
                ('from_customer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, choices=[('NOT_MADE', 'No se preparó'), ('WASTED', 'Se preparó y se tiró'), ('MISTAKE', 'Error de captura')], max_length=10)),
                ('void_note', models.CharField(blank=True, max_length=200)),
                ('stock_applied_at', models.DateTimeField(blank=True, null=True)),
                ('stock_returned_at', models.DateTimeField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.check')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.menuitem')),
                ('comanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='pos.comanda')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.staff')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.staff')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Retiro')], max_length=3)),
                ('amount_cents', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='pos.shift')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.staff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('counted', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.stockcount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.inventoryitem')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='pos.supplier'),
        ),
        migrations.AddField(
            model_name='table',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='pos.zone'),
        ),
    ]
