# Generated by Django 6.1.1 on 2026-09-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_pin_failures'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='tables',
            field=models.ManyToManyField(blank=True, related_name='section_staff', to='pos.table'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('MESERO', 'Mesero'), ('CAJERO', 'Barra'), ('GERENTE', 'Administración')], default='MESERO', max_length=10),
        ),
    ]
