# Generated by Django 6.1.1 on 2026-09-30 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_roles_and_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkline',
            name='stock_deltas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='pos.check'),
        ),
    ]
