from django.urls import path

from . import api, views, views_pay

urlpatterns = [
    path('', views.mapa, name='pos'),
    path('entrar/', views.entrar, name='pos-entrar'),
    path('salir/', views.salir, name='pos-salir'),
    path('mesa/<int:table_id>/', views.mesa, name='pos-mesa'),
    path('rapida/', views.rapida, name='pos-rapida'),
    path('mesa/nueva/', views.mesa_nueva, name='pos-mesa-nueva'),
    path('cuenta/<str:cuenta_id>/', views.cuenta, name='pos-cuenta'),
    path('barra/', views.barra, name='pos-barra'),
    path('caja/', views.caja, name='pos-caja'),
    path('caja/<str:shift_id>/', views.corte, name='pos-corte'),
    path('inventario/', views.inventario, name='pos-inventario'),
    path('inventario/insumo/', views.insumo, name='pos-insumo-nuevo'),
    path('inventario/insumo/<str:item_id>/', views.insumo, name='pos-insumo'),
    path('inventario/compras/', views.compras, name='pos-compras'),
    path('inventario/conteo/', views.conteo, name='pos-conteos'),
    path('inventario/conteo/<str:count_id>/', views.conteo, name='pos-conteo'),
    path('productos/', views.productos, name='pos-productos'),
    path('productos/nuevo/', views.producto, name='pos-producto-nuevo'),
    path('productos/modificadores/', views.modificadores, name='pos-modificadores'),
    path('productos/<str:item_id>/', views.producto, name='pos-producto'),
    path('reportes/', views.reportes, name='pos-reportes'),
    path('personal/', views.personal, name='pos-personal'),
    path('mesas/', views.configurar_mesas, name='pos-mesas'),
    path('impresoras/', views.impresoras, name='pos-impresoras'),
    path('imprimir/', views.pendientes, name='pos-pendientes'),
    path('imprimir/<str:job_id>/', views.imprimir, name='pos-imprimir'),
    # The order screen's JSON.
    path('api/mapa/', api.mapa),
    path('api/cuenta/<str:cuenta_id>/', api.cuenta),
    path('api/cuenta/<str:cuenta_id>/agregar/', api.agregar),
    path('api/cuenta/<str:cuenta_id>/enviar/', api.enviar),
    path('api/cuenta/<str:cuenta_id>/precuenta/', api.precuenta),
    path('api/cuenta/<str:cuenta_id>/descuento/', api.descuento),
    path('api/cuenta/<str:cuenta_id>/personas/', api.personas),
    path('api/cuenta/<str:cuenta_id>/nombre/', api.nombre),
    path('api/cuenta/<str:cuenta_id>/mover/', api.mover),
    path('api/cuenta/<str:cuenta_id>/juntar/', api.juntar),
    path('api/cuenta/<str:cuenta_id>/dividir/', api.dividir),
    path('api/cuenta/<str:cuenta_id>/cancelar/', api.cancelar),
    path('api/cuenta/<str:cuenta_id>/pagar/', api.pagar),
    path('api/cuenta/<str:cuenta_id>/reabrir/', api.reabrir),
    path('api/linea/<str:line_id>/cantidad/', api.linea_cantidad),
    path('api/linea/<str:line_id>/nota/', api.linea_nota),
    path('api/linea/<str:line_id>/cancelar/', api.linea_cancelar),
    # The customer's phone, and the printers.
    path('pagar/<str:token>/', views_pay.pay_page, name='pos-pagar'),
    path('pagar/<str:token>/intent/', views_pay.pay_intent),
    path('pagar/<str:token>/confirmar/', views_pay.pay_confirm),
    path('pagar/<str:token>/listo/', views_pay.pay_done),
    path('print/<str:token>/', views_pay.printer_poll),
]
