import { chromium } from "playwright";
const P = process.argv[2], TOKEN = process.argv[3];
const BASE = "https://iguanacomedy.com";
const b = await chromium.launch();
const p = await (await b.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, locale: "es-MX" })).newPage();
p.on("console", (m) => console.log("  console:", m.type(), m.text().slice(0, 140)));
p.on("pageerror", (e) => console.log("  PAGEERROR:", String(e).slice(0, 200)));
p.on("response", (r) => { if (r.url().includes("/puerta/")) console.log("  net:", r.status(), r.url().replace(BASE, "")); });
await p.goto(`${BASE}/mesas/entrar/`, { waitUntil: "domcontentloaded" });
await p.fill('input[name="username"]', "door");
await p.fill('input[name="password"]', P);
await p.click('button[type="submit"]');
await p.waitForTimeout(2000);
await p.goto(`${BASE}/mesas/puerta/`, { waitUntil: "domcontentloaded" });
await p.waitForTimeout(2000);
console.log("  csrf field present:", await p.locator('input[name=csrfmiddlewaretoken]').count());
console.log("  script tag present:", (await p.content()).includes("verificar"));
await p.fill("#code", TOKEN);
await p.click('#manual button[type="submit"]');
await p.waitForTimeout(2500);
console.log("  verdict:", (await p.locator("#verdict").innerText()).replace(/\n/g, " | "));
console.log("  url now:", p.url().replace(BASE, ""));
await b.close();
