# Generated by Django 6.1.1 on 2026-09-14 22:17

import django.db.models.deletion
import django.utils.timezone
import iguana.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('phone_e164', models.CharField(blank=True, max_length=20)),
                ('subscribed', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('email_marketing_eligible', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, help_text='IMPORT, CONTACT_FORM, ORDER, MEMBERSHIP, SIGN_IN', max_length=30)),
                ('source_event_id', models.CharField(blank=True, max_length=40)),
                ('page_visitor_key', models.CharField(blank=True, max_length=100)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=60)),
                ('stripe_card_brand', models.CharField(blank=True, max_length=20)),
                ('stripe_card_last4', models.CharField(blank=True, max_length=4)),
                ('welcome_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('countries', models.CharField(blank=True, max_length=500)),
                ('cities', models.CharField(blank=True, max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('wallet_credit_cents', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('visitor_key', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('referrer', models.URLField(blank=True, max_length=1000)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('complained_at', models.DateTimeField(blank=True, null=True)),
                ('send_attempts', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='crm.campaign')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact')),
            ],
        ),
        migrations.CreateModel(
            name='ContactListMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.contact')),
                ('contact_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.contactlist')),
            ],
            options={
                'unique_together': {('contact_list', 'contact')},
            },
        ),
        migrations.AddField(
            model_name='contactlist',
            name='contacts',
            field=models.ManyToManyField(related_name='lists', through='crm.ContactListMember', to='crm.contact'),
        ),
        migrations.CreateModel(
            name='InboxConversation',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('channel_type', models.CharField(max_length=20)),
                ('platform', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('handler_mode', models.CharField(blank=True, max_length=20)),
                ('auto_tag', models.CharField(blank=True, max_length=60)),
                ('participant_name', models.CharField(blank=True, max_length=200)),
                ('participant_username', models.CharField(blank=True, max_length=200)),
                ('account_username', models.CharField(blank=True, max_length=200)),
                ('last_message_preview', models.TextField(blank=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='crm.contact')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=10)),
                ('content_type', models.CharField(default='TEXT', max_length=10)),
                ('content', models.TextField(blank=True)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.inboxconversation')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
    ]
