# Generated by Django 6.1.1 on 2026-09-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_longer_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='browser_language',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='contact',
            name='geo_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contact',
            name='geo_country',
            field=models.CharField(blank=True, help_text='From their IP address', max_length=2),
        ),
        migrations.AddField(
            model_name='contact',
            name='geo_region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='locale',
            field=models.CharField(blank=True, help_text='Site language they used: en or es', max_length=5),
        ),
        migrations.AddField(
            model_name='contact',
            name='time_zone',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='contact',
            name='source',
            field=models.CharField(blank=True, help_text='IMPORT, CONTACT_FORM, NEWSLETTER, ORDER, MEMBERSHIP, SIGN_IN', max_length=30),
        ),
    ]
