# Generated by Django 6.1.1 on 2026-09-24 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_contact_browser_language_contact_geo_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('campaign_id', models.CharField(max_length=40)),
                ('campaign_name', models.CharField(max_length=200)),
                ('kind', models.CharField(default='PAID', help_text='Whether this campaign sells free seats or tickets.', max_length=8)),
                ('spend_cents', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('reported_purchases', models.PositiveIntegerField(default=0, help_text="Meta's own count, which is not ours.")),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-day', 'campaign_name'],
                'constraints': [models.UniqueConstraint(fields=('day', 'campaign_id'), name='one_row_per_campaign_per_day')],
            },
        ),
    ]
