# Generated by Django 6.1.1 on 2026-09-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_adspend'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adspend',
            name='one_row_per_campaign_per_day',
        ),
        migrations.AddField(
            model_name='adspend',
            name='frequency',
            field=models.FloatField(default=0, help_text='Impressions per person. Meta reports it; never summed.'),
        ),
        migrations.AddField(
            model_name='adspend',
            name='reach',
            field=models.PositiveIntegerField(default=0, help_text='People who saw it at least once, deduplicated.'),
        ),
        migrations.AddField(
            model_name='adspend',
            name='window',
            field=models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week')], default='DAY', max_length=5),
        ),
        migrations.AddConstraint(
            model_name='adspend',
            constraint=models.UniqueConstraint(fields=('day', 'window', 'campaign_id'), name='one_row_per_campaign_per_window'),
        ),
    ]
