# Generated by Django 6.1.1 on 2026-10-09 19:41

import django.db.models.deletion
import django.utils.timezone
import iguana.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_adspend_one_row_per_campaign_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicSubmission',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_TALKS', 'In talks'), ('BOOKED', 'Booked'), ('DECLINED', 'Declined')], default='NEW', max_length=10)),
                ('staff_notes', models.TextField(blank=True, help_text='Ours only, never shown to the comedian.')),
                ('lang', models.CharField(default='en', help_text='The language they filled the form in.', max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('stage_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone or WhatsApp', max_length=40)),
                ('instagram', models.CharField(blank=True, max_length=200)),
                ('tiktok', models.CharField(blank=True, max_length=200)),
                ('links', models.TextField(blank=True, help_text='YouTube, specials, other clips')),
                ('home_city', models.CharField(blank=True, max_length=200)),
                ('languages', models.CharField(blank=True, help_text='Languages they perform in', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('requested_dates', models.JSONField(blank=True, default=list, help_text='ISO dates they would like, in order')),
                ('availability', models.TextField(blank=True)),
                ('show_name', models.CharField(blank=True, max_length=200)),
                ('draw', models.TextField(blank=True, help_text='Expected draw, followers')),
                ('ticket_price', models.CharField(blank=True, max_length=200)),
                ('guests', models.TextField(blank=True, help_text='Do they bring an opener or guests')),
                ('notes', models.TextField(blank=True)),
                ('consent_at', models.DateTimeField(help_text='When they agreed we may use the photos and clips to promote the show')),
                ('ip', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComicFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PHOTO', 'Photo'), ('CLIP_30', 'Clip, about 30 seconds'), ('CLIP_60', 'Clip, about 1 minute'), ('CLIP_LONG', 'Clip, 2 to 5 minutes')], max_length=10)),
                ('original_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(help_text="File name inside the submission's folder", max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Read with ffprobe after upload, when available', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crm.comicsubmission')),
            ],
            options={
                'ordering': ['kind', 'id'],
            },
        ),
    ]
