# Generated by Django 6.1.1 on 2026-09-14 22:17

import django.db.models.deletion
import django.utils.timezone
import iguana.ids
import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('token', models.CharField(default=iguana.ids.new_token, max_length=60, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField(default=sales.models._login_expiry)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('benefits', models.JSONField(blank=True, default=list, help_text='["Two free tickets", ...]')),
                ('currency', models.CharField(default='mxn', max_length=3)),
                ('monthly_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('annual_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('lifetime_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('pass_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('pass_days', models.PositiveIntegerField(blank=True, null=True)),
                ('free_tickets_per_order', models.PositiveIntegerField(default=2)),
                ('guest_discount_percent', models.PositiveIntegerField(default=10)),
                ('stripe_product_id', models.CharField(blank=True, max_length=60)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired'), ('PAST_DUE', 'Past Due')], default='PENDING', max_length=10)),
                ('source', models.CharField(blank=True, help_text='RECURRING, LIFETIME, PASS, CODE, MANUAL', max_length=20)),
                ('billing_interval', models.CharField(blank=True, max_length=10)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('credit_balance_cents', models.IntegerField(default=0)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='crm.contact')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='sales.membershipplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransfer',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='mxn', max_length=3)),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transfers_received', to='crm.contact')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transfers_sent', to='crm.contact')),
                ('from_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.membership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('total_amount_cents', models.PositiveIntegerField(default=0)),
                ('discount_amount_cents', models.PositiveIntegerField(default=0)),
                ('credits_applied_cents', models.PositiveIntegerField(default=0)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=40)),
                ('event_name', models.CharField(blank=True, help_text='Snapshot, kept when the event row is missing.', max_length=200)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=80)),
                ('public_view_token', models.CharField(default=iguana.ids.new_token, max_length=60, unique=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('attribution', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm.contact')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_cents', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order')),
                ('ticket_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.tickettype')),
            ],
        ),
        migrations.CreateModel(
            name='RedeemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('kind', models.CharField(choices=[('membership', 'Membership'), ('credits', 'Credits')], max_length=12)),
                ('days', models.PositiveIntegerField(blank=True, help_text='Membership length granted', null=True)),
                ('amount_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='mxn', max_length=3)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.membershipplan')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('ticket_type_name', models.CharField(max_length=120)),
                ('checkin_token', models.CharField(default=iguana.ids.new_token, max_length=80, unique=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='sales.order')),
            ],
        ),
    ]
