# Generated by Django 6.1.1 on 2026-09-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_order_pay_at_door_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='locale',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
