# Generated by Django 6.1.1 on 2026-09-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_order_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='benefits_es',
            field=models.JSONField(blank=True, default=list, help_text='["Dos boletos gratis", ...]'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='description_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='name_es',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
