# Generated by Django 6.1.1 on 2026-09-22 00:19

from django.db import migrations, models


def mark_existing_addons(apps, schema_editor):
    """Existing rows default to False, which would call every drink already sold a seat.

    Read it back off the ticket type while that link still exists. A line whose type has since been deleted stays
    False, which is the safe way round: it keeps its ticket rather than silently losing one.
    """
    OrderItem = apps.get_model('sales', 'OrderItem')
    OrderItem.objects.filter(ticket_type__is_addon=True).update(is_addon=True)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_membershipplan_benefits_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_addon',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_addons, migrations.RunPython.noop),
    ]
