# Generated by Django 6.1.1 on 2026-09-22 01:58

import django.db.models.deletion
import django.utils.timezone
import iguana.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_menucategory_menuitem'),
        ('sales', '0006_orderitem_is_addon_db_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOrder',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('table_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('total_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='mxn', max_length=3)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('locale', models.CharField(default='en', max_length=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TableOrderItem',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price_cents', models.PositiveIntegerField()),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.tableorder')),
            ],
        ),
    ]
