# Generated by Django 6.1.1 on 2026-09-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_tableorder_tableorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='follow_up_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
