# Generated by Django 6.1.1 on 2026-09-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_order_follow_up_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tableorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('DELIVERED', 'Delivered'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10),
        ),
    ]
