# Generated by Django 6.1.1 on 2026-09-24 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_tickettype_sold_elsewhere'),
        ('sales', '0009_tableorder_paid_at_alter_tableorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_orders', to='catalog.event'),
        ),
    ]
