# Generated by Django 6.1.1 on 2026-09-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_tableorder_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='stock_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
