# Generated by Django 6.1.1 on 2026-09-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_tableorder_stock_applied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorderitem',
            name='stock_returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tableorderitem',
            name='void_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tableorderitem',
            name='void_reason',
            field=models.CharField(blank=True, choices=[('NOT_MADE', 'No se preparó'), ('WASTED', 'Se preparó y se tiró')], max_length=10),
        ),
        migrations.AddField(
            model_name='tableorderitem',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tableorderitem',
            name='voided_by',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
