# Generated by Django 6.1.1 on 2026-09-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_tableorderitem_stock_returned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='guest_name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
