# Generated by Django 6.1.1 on 2026-09-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_tableorder_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, db_index=True, help_text="Blank for our own sales; 'goliiive' for an imported promoter list.", max_length=20),
        ),
    ]
