# Generated by Django 6.1.1 on 2026-09-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
