# Generated by Django 6.1.1 on 2026-09-26 03:11

import django.db.models.deletion
import django.utils.timezone
import iguana.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_floorsettings_labels'),
        ('sales', '0015_tableorder_closed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablePayment',
            fields=[
                ('id', models.CharField(default=iguana.ids.new_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('table_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('ABANDONED', 'Abandoned')], default='PENDING', max_length=10)),
                ('bill_cents', models.PositiveIntegerField(default=0)),
                ('tip_cents', models.PositiveIntegerField(default=0)),
                ('tip_percent', models.PositiveSmallIntegerField(default=0)),
                ('total_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='mxn', max_length=3)),
                ('locale', models.CharField(default='es', max_length=5)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=120)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_payments', to='catalog.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tableorder',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.tablepayment'),
        ),
    ]
